# Generated by Django 6.0.2 on 2026-03-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(default='new', max_length=100),
            preserve_default=False,
        ),
    ]
